//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetManiaServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public int IdAgenda { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdAnimal { get; set; }
        public Nullable<int> IdServico { get; set; }
        public Nullable<int> IdPetShop { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual PetShop PetShop { get; set; }
        public virtual Servico Servico { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
