//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetManiaServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public Nullable<int> IdPetShop { get; set; }
        public Nullable<int> IdGrupoUsuario { get; set; }
    
        public virtual GrupoUsuario GrupoUsuario { get; set; }
        public virtual PetShop PetShop { get; set; }
    }
}
